# permissions for end users to edit clusterinformations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinformation-editor-role
rules:
- apiGroups:
  - ferry.zsm.io
  resources:
  - clusterinformations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ferry.zsm.io
  resources:
  - clusterinformations/status
  verbs:
  - get
