---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - hubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - hubs/finalizers
  verbs:
  - update
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - hubs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routes/finalizers
  verbs:
  - update
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
