# permissions for end users to edit routepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routepolicy-editor-role
rules:
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies/status
  verbs:
  - get
