# permissions for end users to view routepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routepolicy-viewer-role
rules:
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traffic.ferryproxy.io
  resources:
  - routepolicies/status
  verbs:
  - get
