apiVersion: ferry.zsm.io/v1alpha1
kind: ClusterInformation
metadata:
  name: clusterinformation-sample
spec:
  kubeconfig: <kubeconfig> #<base64-encoded-kubeconfig-data:data-plane-cluster-1>
  egress:
    serviceName: "ferry-tunnel"
    serviceNamespace: "ferry-tunnel-system"
    port: 31087
    defaultProxies:
      - clusterName: "cluster1"
  ingress:
    ip: <ingress ip> #<host-ip>
    port: 31087
    proxies:
      cluster2:
        - clusterName: "cluster1"
