apiVersion: ferry.zsm.io/v1alpha1
kind: FerryPolicy
metadata:
  name: ferrypolicy-sample
spec:
  rules:
    
    # mapping cluster1's label matched app=web1 to cluster2's same name and namespace
    - exports:
        - clusterName: cluster1
          match:
            labels:
              app: "web1"
      imports:
        - clusterName: cluster2

    # mapping cluster1's label matched app=web2 in default namespaces to cluster2's same name and namespace
    - exports:
        - clusterName: cluster2
          match:
            namespace: default
            labels:
              app: "web-2"
      imports:
        - clusterName: cluster1

    # mapping cluster2's kubernetes.default to cluster2 kubernetes-cluster2.default
    - exports:
        - clusterName: cluster2
          match:
            namespace: default
            name: kubernetes
      imports:
        - clusterName: cluster1
          match:
            namespace: default
            name: kubernetes-cluster2
